komtek/api/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from .views import HandBookViewSet, ItemViewSet

app_name = 'api-v1'

router_v1 = SimpleRouter()
router_v1.register(r'handbooks', HandBookViewSet, basename='handbook')
router_v1.register(
    r'handbooks/(?P<handbook_id>\d+)/items', ItemViewSet, basename='item'
)

urlpatterns = [
    path('v1/', include(router_v1.urls)),
]

komtek/handbooks/urls.py
from django.urls import path

from . import views

app_name = 'handbooks'

urlpatterns = [
    path('', views.index, name='index'),
    path('handbooks/', views.handbooks, name='handbooks'),
    path('handbooks/<int:handbook_id>/',
         views.handbook_view, name='handbook_view'),
]

komtek/komtek/urls.py
from django.conf.urls import handler404, handler500, url
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

handler404 = 'handbooks.views.page_not_found'
handler500 = 'handbooks.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api-v1')),
    path('auth/', include('djoser.urls')),
    # JWT-эндпоинты, для управления JWT-токенами:
    path('auth/', include('djoser.urls.jwt')),
    path('', include('handbooks.urls', namespace='handbooks')),
]

schema_view = get_schema_view(
    openapi.Info(
        title="HandBooks API",
        default_version='v1',
        description="Документация приложения handbooks проекта test-task-KOMTEK",
        # terms_of_service="URL страницы с пользовательским соглашением",
        contact=openapi.Contact(email="admin@komtek.ru"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns += [
    url(r'^swagger(?P<format>\.json|\.yaml)$',
        schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0),
        name='schema-redoc'),
]

komtek/handbooks/models.py
from django.db import models


class HandBook(models.Model):
    """Модель для справочника."""

    text = models.TextField('Наименование', max_length=200)
    name = models.CharField('Короткое наименование', max_length=100)
    description = models.TextField('Описание')
    version = models.CharField(
        'Версия', unique=True, blank=False, max_length=50
    )
    pub_date = models.DateTimeField(
        'Дата публикации', auto_now_add=True, db_index=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Справочник'
        verbose_name_plural = 'Справочники'

    def __str__(self) -> str:
        return self.name


class Item(models.Model):
    """Модель для элементов справочника."""

    handbook = models.ForeignKey(
        HandBook, on_delete=models.CASCADE,
        related_name='items', verbose_name='Справочник'
    )
    code = models.CharField(
        'Код элемента', unique=True, blank=False, max_length=50
    )
    value = models.TextField('Значение элемента', blank=False)

    class Meta:
        verbose_name = 'Элемент справочника'
        verbose_name_plural = 'Элементы справочника'

komtek/handbooks/forms.py
from django.forms import ModelForm

from .models import HandBook, Item


class HandBookForm(ModelForm):
    """Форма для справочников."""

    class Meta:
        model = HandBook
        fields = ('text', 'name', 'description', 'version',)


class ItemForm(ModelForm):
    """Форма для элементов справочника."""

    class Meta:
        model = Item
        fields = ('code', 'value',)

komtek/api/views.py
from django.shortcuts import get_object_or_404
from rest_framework import viewsets
from rest_framework.pagination import PageNumberPagination
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from handbooks.models import HandBook

from .serializers import HandBookSerializer, ItemSerializer


class HandBookViewSet(viewsets.ModelViewSet):
    queryset = HandBook.objects.all()
    serializer_class = HandBookSerializer
    permission_classes = (IsAuthenticatedOrReadOnly,)
    http_method_names = ('get', 'head', 'options',)
    pagination_class = PageNumberPagination


class ItemViewSet(viewsets.ModelViewSet):
    serializer_class = ItemSerializer
    permission_classes = (IsAuthenticatedOrReadOnly,)
    http_method_names = ('get', 'head', 'options',)
    pagination_class = PageNumberPagination

    def get_queryset(self):
        handbook = get_object_or_404(
            HandBook, id=self.kwargs['handbook_id'],
        )
        return handbook.items.all()

    def perform_create(self, serializer):
        handbook = get_object_or_404(
            HandBook, id=self.kwargs['handbook_id'],
        )
        serializer.save(handbook=handbook)

komtek/handbooks/views.py
from django.core.paginator import Paginator
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render

from .models import HandBook, Item


def index(request) -> HttpResponse:
    """view-функция для главной страницы."""
    return render(request, 'index.html')


def handbooks(request) -> HttpResponse:
    """view-функция для просмотра всех справочников."""
    handbooks = HandBook.objects.all()
    paginator = Paginator(handbooks, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {'page': page}
    return render(request, 'handbooks/handbooks.html', context)


def handbook_view(request, handbook_id) -> HttpResponse:
    """view-функция для просмотра справочника."""
    handbook = get_object_or_404(HandBook, id=handbook_id)
    items = Item.objects.filter(handbook=handbook)
    paginator = Paginator(items, 20)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {'handbook': handbook, 'page': page}
    return render(request, 'handbooks/handbook.html', context)


def page_not_found(request, exception) -> HttpResponse:
    return render(request, 'misc/404.html', {'path': request.path}, status=404)


def server_error(request) -> HttpResponse:
    return render(request, 'misc/500.html', status=500)

komtek/handbooks/templates/handbooks/card_handbook.html
<div class="card mb-3 mt-1 shadow-sm">
  <div class="col-md-9">
    <div class="card-body">
      <p class="card-text">
      <p class="lead"><a href="{% url 'handbooks:handbook_view' handbook.id %}">{{ handbook.name }}</a></p>
      <h6>{{ handbook.text|linebreaksbr }}</h6>
      <p>{{ handbook.description|linebreaksbr }}</p>
      <p>Версия: {{ handbook.version|linebreaksbr }}</p>
      </p>
      <hr>
      <div class="d-flex justify-content-between align-items-center">
        <small class="text-muted">{{ handbook.pub_date|date:"d E Y" }} г.</small>
      </div>
    </div>
  </div>
</div>

komtek/handbooks/templates/handbooks/handbook.html
{% extends "base.html" %}
{% block title %}Справочник{% endblock %}
{% block header %}Справочник и его элементы{% endblock %}
{% block content %}

<div class="container">

      <p class="lead"><a href="{% url 'handbooks:handbooks' %}">Все справочники</a></p>

  <div class="card mb-3 mt-1 shadow-sm">
    <div class="col-md-9">
      <div class="card-body">
        <p class="card-text">
        <h6>{{ handbook.name }}</h6>
        <p>{{ handbook.text }}</p>
        <p>{{ handbook.description }}</p>
        <p>Версия: {{ handbook.version }}</p>
        </p>
        <hr>
        <div class="d-flex justify-content-between align-items-center">
          <small class="text-muted">{{ handbook.pub_date|date:"d E Y" }} г.</small>
        </div>
      </div>
    </div>
  </div>
  {% for item in page %}
  <div class="card mb-3 mt-1 shadow-sm">
    <div class="col-md-9">
      <div class="card-body">
        <p class="card-text">
        <p>{{ item.handbook }}</p>
        <p>{{ item.code }}</p>
        <p>{{ item.value }}</p>
        </p>
      </div>
    </div>
  </div>
  {% endfor %}
  {% include "misc/paginator.html" %}
</div>

{% endblock %}

komtek/handbooks/templates/handbooks/handbooks.html
{% extends "base.html" %}
{% block title %}Справочники{% endblock %}
{% block header %}Все справочники{% endblock %}
{% block content %}

<div class="container">

  {% for handbook in page %}
  {% include "handbooks/card_handbook.html" %}
  {% endfor %}

  {% include "misc/paginator.html" %}
</div>

{% endblock %}

komtek/templates/base.html
<!doctype html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}Справочник{% endblock %}</title>
  <!-- Загрузка статики -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
  <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>

<body>
  <main>
    <div class="container">
      <h1>{% block header %}Справочник{% endblock %}</h1>
      {% block content %}
      <!-- Содержимое страницы -->
      {% endblock %}
    </div>
  </main>
</body>

</html>

komtek/templates/index.html
{% extends "base.html" %}
{% block title %}Главная страница{% endblock %}
{% block header %}Главная страница{% endblock %}
{% block content %}

<div class="container">
  <hr>
  <p>Не желаете ли перейти к справочникам?</p>
  <p class="lead"><a href="{% url 'handbooks:handbooks' %}">Справочники</a></p>
  <br>
  <hr>
  <p>Ещё у нас есть API:</p>
  <p class="lead"><a href="api/v1/handbooks/">api v1</a></p>
  <p>Документация:</p>
  <p class="lead"><a href="{% url 'schema-swagger-ui' %}" target="_blank">Swagger</a></p>
  <p class="lead"><a href="{% url 'schema-redoc' %}" target="_blank">Redoc</a></p>
</div>

{% endblock %}

komtek/templates/misc/paginator.html
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; туда</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; туда</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">сюда &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">сюда &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}